version: "3"

volumes:
  mysql_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
      - DB_USER=romm-user # Should match MARIADB_USER in mariadb
      - DB_PASSWD=cxb23se6 # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY=15bc86c1651738233ee590ccf9c3a60704c168018a22febe1c10ff3b0939089eb
      - SCREENSCRAPER_USER=Janderas70 # These are the recommended metadata providers
      - SCREENSCRAPER_PASSWORD=cxb23se6 # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
      - RETROACHIEVEMENTS_API_KEY=G4MQ925Z3ewtcyapflF16xsAo8amIxnD # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
      - STEAMGRIDDB_API_KEY=3cbfff0089ab8895a589ed8a849150b1 # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
      - HASHEOUS_API_ENABLED=false # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
    volumes:
      - /romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /romm_redis_data:/redis-data # Cached data for background tasks
      - /library:/romm/library # Your game library. Check https://docs.romm.app/latest/Getting-Started/Folder-Structure/ for more details.
      - /assets:/romm/assets # Uploaded saves, states, etc.
      - /config:/romm/config # (Optional) Path where config.yml is stored
    ports:
      - 80:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root # Use a unique, secure password
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=cxb23se6
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
